-- Intentionally left as a no-op.
--
-- Background:
-- - New installs now create `booking_objects` with `full_day_start_time` and
--   `full_day_end_time` directly in 001_initial_schema.sql.
-- - Running ADD COLUMN here would fail with "duplicate column name" on fresh
--   databases.
--
-- Backward compatibility:
-- - `scripts/provision_d1.mjs` and runtime init now both ensure these columns
--   exist for older databases that might still miss them.
